apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: us.icr.io/sn-labs-vupadhyay382/accounts:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: DATABASE_URI
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
